[linters]
disable-all = true
enable = [
    "goimports",
    "gosimple",
    "govet",
    "ineffassign",
    "revive",
    "staticcheck",
    "unused",
]

[linters-settings.revive]
ignore-generated-header = true
