name: check-pr-title
on:
  pull_request:
    branches: [main]
  pull_request_target:
    types: [opened, edited, synchronize, reopened]
    branches: [main]
jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: thehanimo/pr-title-checker@v1.4.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false
          configuration_path: .github/pr-title-config.json
