name: release
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Bump version
        id: bump-version
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          MAJOR_STRING_TOKEN: "break:"
          MINOR_STRING_TOKEN: "feat:"
          PATCH_STRING_TOKEN: "fix:"
          NONE_STRING_TOKEN: "no-release:"
      - name: Release next version
        if: ${{ steps.bump-version.outputs.old_tag != '' }}
        uses: ncipollo/release-action@v1
        with:
          draft: true
          generateReleaseNotes: true
          makeLatest: true
          tag: ${{ steps.bump-version.outputs.new_tag }}
